version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12

    steps:
      - checkout

      - run: npm ci
      - run: npm run build
      - run: npm start &
      - run: npx cypress run

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
